In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pulp import *
import pandas as pd
from sklearn.neighbors import DistanceMetric
from math import radians
import math as math

Check which Facility Location Model fits best:

- 4.4 Capacitated p-Median Facility Location Problem = Discrete Model, which means it needs candidate locations. Candidate Locations are the same as Customer locations
    - 
    
- 4.5.1 Symmetrical Total Covering Problem
- Try the Continous Location Model for Multiple Locations from DAW Project

Try the single location model first for practice (DAW)

![CLM1](https://i.imgur.com/mb7ep08.png)

I cant use this function with pulp since its not linear, but i could determine the second part of the function outside of pulp

For that I would need some solution space tho, e.g. Candidates which kind of defeats the purpose of this facility location model

In [ ]:
5**2

In [ ]:
# Construct set of all potential Customers N

# create index
C_ID = ["C1", "C2", "C3", "C4", "C5"]

# Set the demand dj
demand_C = [5, 5, 5, 5, 5]

# Position of customers
lat_C = [49.78981985, 49.79961774, 49.75060158, 49.79996773, 49.76905279]
lon_C = [9.964805881, 9.873297251, 9.919076627, 9.889586523, 9.913514194]

c_tuples = list(zip(C_ID, demand_C, lat_C, lon_C))

set_of_all_customers = pd.DataFrame(c_tuples, columns = ["C_ID", "demand_C", "lat_C", "lon_C"])
set_of_all_customers.set_index("C_ID", inplace = True)
set_of_all_customers

In [ ]:
N = set_of_all_customers.index.values
N

In [ ]:
model1 = LpProblem("CLM1", LpMinimize)

In [ ]:
x = LpVariable(name = "x", cat = "Continuous")
x

In [ ]:
y = LpVariable(name = "y", cat = "Continuous")
y

In [ ]:
#Demand and Distance

demand_d = lpSum(set_of_all_customers.loc[n].demand_C * math.sqrt(((x - set_of_all_customers.loc[n].lat_C) * (x - set_of_all_customers.loc[n].lat_C))
                                                                  + (y - set_of_all_customers.loc[n].lon_C) * (y - set_of_all_customers.loc[n].lon_C)) for n in N)
demand_d

<font size="6">**DAW Continuous Location Model for Multiple Locations**</font><br>
![CLM](https://i.imgur.com/1jiL7ux.png)

In [ ]:
model = LpProblem("CLM", LpMinimize)

In [ ]:
# Construct set of all potential Customers N

# create index
C_ID = ["C1", "C2", "C3", "C4", "C5"]

# Set the demand dj
demand_C = [5, 5, 5, 5, 5]

# Position of customers
lat_C = [49.78981985, 49.79961774, 49.75060158, 49.79996773, 49.76905279]
lon_C = [9.964805881, 9.873297251, 9.919076627, 9.889586523, 9.913514194]

c_tuples = list(zip(C_ID, demand_C, lat_C, lon_C))

set_of_all_customers = pd.DataFrame(c_tuples, columns = ["C_ID", "demand_C", "lat_C", "lon_C"])
set_of_all_customers.set_index("C_ID", inplace = True)
set_of_all_customers

In [ ]:
N = set_of_all_customers.index.values
N

In [ ]:
# Create a mostly empty DF for the potential Warehouses

#create an index
DC_ID = ["DC_1", "DC_2", "DC_3", "DC_4", "DC_5"] #, 2, 3, 4]


#Position of the DCs
lat_DC = [0,0,0,0,0]# 49.81613668, 49.78379436, 49.74101263]
lon_DC = [0,0,0,0,0]# 9.897654496, 9.896245726, 9.88898842]

dc_tuples = list(zip(DC_ID, lat_DC, lon_DC))

set_of_all_DC = pd.DataFrame(dc_tuples, columns = ["DC_ID", "lat_DC", "lon_DC"])
set_of_all_DC.set_index("DC_ID", inplace = True)
set_of_all_DC

In [ ]:
M = set_of_all_DC.index.values
M

In [ ]:
# Define C
cost = [0.5]
cost

In [ ]:
z = LpVariable.dicts(name = "z", indexs= (M,N), cat = "Binary")
z

In [ ]:
for m in M:
    for n in N:
        z[m][n]

Discrete Model



<font size="6">**Discrete Model - Capacitated p-Median Facility Location Problem**</font><br>
![](https://i.imgur.com/Nd4031p.png)

Set of customers and PuP is identical

- Decision Variables:
    - yij = if customer i is assigned to PuP j 1;0
    - xj = if PuP j is opened or not 1;0
- Parameters:
    - P = Number of PuPs
    - cij = Shipment cost from PuP to Customer
    - di = Demand of customer i
    - qj = Capacity of PuP j

In [ ]:
# Construct set of all potential Customers i

# create index
C_ID = ["C1", "C2", "C3", "C4", "C5"]

# Set the demand dj
demand_C = [5, 5, 5, 5, 5]

# Position of customers
lat_C = [49.78981985, 49.79961774, 49.75060158, 49.79996773, 49.76905279]
lon_C = [9.964805881, 9.873297251, 9.919076627, 9.889586523, 9.913514194]

c_tuples = list(zip(C_ID, demand_C, lat_C, lon_C))

set_of_all_customers = pd.DataFrame(c_tuples, columns = ["C_ID", "demand_C", "lat_C", "lon_C"])
set_of_all_customers.set_index("C_ID", inplace = True)
set_of_all_customers

- Try to simulate new customer data. Especially the coordinates have to be between a certain bound which I will find out from google maps
    - Top left : 49.817523, 9.878976
    - Top right : 49.815197, 9.985750
    - Bottom left: 49.731885, 9.936654
    - Bottom right: 49.719637, 9.974656

Could also use shapely to simulate coordinates in a polygon

import random
from shapely.geometry import Point

def generate_random(number, polygon):
    points = []
    minx, miny, maxx, maxy = polygon.bounds
    while len(points) < number:
        pnt = Point(random.uniform(minx, maxx), random.uniform(miny, maxy))
        if polygon.contains(pnt):
            points.append(pnt)
    return points

In [2]:
import osmnx as ox
ox.config(use_cache=True, log_console=True)

In [3]:
import matplotlib as plt
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, LineString
import networkx as nx

In [ ]:
warnings.filterwarnings("ignore")

place = {"city": "Wuerzburg", "country": "Germany"}
G = ox.graph_from_place(place, network_type = "drive")
#C3 49.758535, 9.932180
# DC Coords
coord_DC = (49.719637, 9.974656)
# Customer Coords
#coord_C1 = (49.78981985, 9.964805881)
#coord_C2 = (49.79961774, 9.873297251)
#coord_C3 = (49.758535, 9.932180)
#coord_C4 = (49.79996773, 9.889586523)
#coord_C5 = (49.76905279, 9.913514194)

DC_1 = ox.get_nearest_node(G, coord_DC)


nodes, edges = ox.graph_to_gdfs(G, nodes=True, edges=True)

ns = [120 if node == DC_1 else 5 for node in G.nodes()]

nc = []
for node in G.nodes():
    if node == DC_1:
        nc.append("red")
    else:
        nc.append("white")
        
fig, ax = ox.plot_graph(G, node_size = ns, edge_linewidth = 0.5, node_color = nc, figsize = (22,22), bgcolor = "black")

<font size="6">**New idea, just use the all of the nodes as customers. Would be 2772 Customers and 2772 potential warehouses**

<font size="6">**Tried with all 2772 but that created fatal RAM error and an output that was 500MB large**

<font size="6">**Try with 50 Customers now**</font>

In [4]:
G = ox.graph_from_place("Wuerzburg, Germany", network_type = "drive")
gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)
gdf_nodes

,y,x,street_count,highway,ref,geometry
osmid,,,,,,
580993,49.751875,9.933932,3,NaN,NaN,POINT (9.93393 49.75188)
10799058,49.751452,9.926904,3,NaN,NaN,POINT (9.92690 49.75145)
10799066,49.753819,9.928881,3,NaN,NaN,POINT (9.92888 49.75382)
10799083,49.751798,9.927970,3,NaN,NaN,POINT (9.92797 49.75180)
10799085,49.751011,9.927733,3,NaN,NaN,POINT (9.92773 49.75101)
...,...,...,...,...,...,...
8917704493,49.804200,9.918704,3,NaN,NaN,POINT (9.91870 49.80420)
8917704495,49.804163,9.918820,3,NaN,NaN,POINT (9.91882 49.80416)
8917704496,49.804228,9.918785,4,NaN,NaN,POINT (9.91878 49.80423)
8917704497,49.804300,9.918692,4,NaN,NaN,POINT (9.91869 49.80430)
8981470540,49.794116,9.928858,1,NaN,NaN,POINT (9.92886 49.79412)

In [5]:
# Could use this as customers (all nodes from OSMNX in Würzburg)
nodes_df = gdf_nodes[["y", "x"]].copy()
nodes_df.columns = ["lat", "lon"]
nodes_df

                  lat       lon
osmid
580993      49.751875  9.933932
10799058    49.751452  9.926904
10799066    49.753819  9.928881
10799083    49.751798  9.927970
10799085    49.751011  9.927733
...               ...       ...
8917704493  49.804200  9.918704
8917704495  49.804163  9.918820
8917704496  49.804228  9.918785
8917704497  49.804300  9.918692
8981470540  49.794116  9.928858

[2772 rows x 2 columns]

In [37]:
sample_nodes_df = nodes_df.sample(n = 50, random_state= 2)
sample_nodes_df.head()

                 lat       lon
osmid
316910925  49.805047  9.963641
360648490  49.721933  9.973095
253340629  49.809767  9.980707
25588713   49.767957  9.938838
18177997   49.790385  9.909982

In [46]:
C_ID = list(range(1,51))
osmid = list(sample_nodes_df.index.values)

In [47]:
sample_nodes_df = sample_nodes_df.rename(index=dict(zip(osmid,C_ID)))

In [48]:
# Create a Customer DF with demands and coordinates
sample_nodes_df.index.name = "C_ID"
sample_nodes_df.head()

            lat       lon  Demand_C  Capacity_pup
C_ID
1     49.805047  9.963641         5           100
2     49.721933  9.973095         5           100
3     49.809767  9.980707         5           100
4     49.767957  9.938838         5           100
5     49.790385  9.909982         5           100

In [49]:
mylist = [5] * 50

set_of_all_customers = sample_nodes_df
set_of_all_customers['Demand_C'] = mylist
set_of_all_customers.head()

            lat       lon  Demand_C  Capacity_pup
C_ID
1     49.805047  9.963641         5           100
2     49.721933  9.973095         5           100
3     49.809767  9.980707         5           100
4     49.767957  9.938838         5           100
5     49.790385  9.909982         5           100

In [50]:
I = set_of_all_customers.index.values
I

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
      dtype=int64)

In [ ]:
set_of_all_customers.loc[2].Demand_C
#set_of_all_pup.loc[2].Capacity_pup
#type(set_of_all_customers)

In [52]:
set_of_all_pup = sample_nodes_df
cap_list = [100] * 50
set_of_all_pup["Capacity_pup"] = cap_list
set_of_all_pup.drop('Demand_C', axis=1, inplace=True)
set_of_all_pup.index.name = "PuP_ID"
set_of_all_pup.head()

              lat       lon  Capacity_pup
PuP_ID
1       49.805047  9.963641           100
2       49.721933  9.973095           100
3       49.809767  9.980707           100
4       49.767957  9.938838           100
5       49.790385  9.909982           100

In [53]:
J = set_of_all_pup.index.values
J

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
      dtype=int64)

In [22]:
model = LpProblem("CpMFLP", LpMinimize)

In [23]:
x = LpVariable.dicts(name = "x", indexs = J, cat = "Binary")
#x

In [24]:
y = LpVariable.dicts(name = "y", indexs = (I,J), cat = "Binary")
#y

Create Distance matrix now between all the points

In [54]:
DF = set_of_all_pup
DF['PuP_ID'] = DF.index
DF['lat'] = np.radians(DF['lat'])
DF['lon'] = np.radians(DF['lon'])
DF

             lat       lon  Capacity_pup  PuP_ID
PuP_ID
1       0.869262  0.173898           100       1
2       0.867811  0.174063           100       2
3       0.869344  0.174196           100       3
4       0.868615  0.173465           100       4
5       0.869006  0.172962           100       5
6       0.868101  0.173841           100       6
7       0.868191  0.173361           100       7
8       0.869483  0.173964           100       8
9       0.869616  0.173998           100       9
10      0.868973  0.173984           100      10
11      0.869386  0.173167           100      11
12      0.869062  0.172848           100      12
13      0.869110  0.174206           100      13
14      0.869590  0.174037           100      14
15      0.869050  0.172847           100      15
16      0.869179  0.173247           100      16
17      0.869117  0.174259           100      17
18      0.868135  0.173878           100      18
19      0.868514  0.173480           100      19
20      0.867854  0.174054           100      20
21      0.869031  0.173637           100      21
22      0.869616  0.174202           100      22
23      0.869120  0.173287           100      23
24      0.868443  0.173613           100      24
25      0.868453  0.173324           100      25
26      0.869530  0.173838           100      26
27      0.868536  0.173361           100      27
28      0.868923  0.173349           100      28
29      0.869253  0.174402           100      29
30      0.869011  0.173398           100      30
31      0.868227  0.173815           100      31
32      0.869056  0.173647           100      32
33      0.867794  0.173991           100      33
34      0.868917  0.172963           100      34
35      0.868820  0.173203           100      35
36      0.868250  0.173437           100      36
37      0.869204  0.174171           100      37
38      0.869558  0.173960           100      38
39      0.869304  0.172518           100      39
40      0.868497  0.173884           100      40
41      0.868020  0.173788           100      41
42      0.868939  0.173169           100      42
43      0.869283  0.173842           100      43
44      0.868979  0.173349           100      44
45      0.868671  0.173774           100      45
46      0.868815  0.173197           100      46
47      0.869359  0.174118           100      47
48      0.868953  0.173339           100      48
49      0.869275  0.172768           100      49
50      0.869224  0.173189           100      50

In [26]:
dist = DistanceMetric.get_metric("haversine")

In [27]:
DF[["lat", "lon"]].to_numpy()

array([[0.86926206, 0.17389835],
       [0.86781144, 0.17406335],
       [0.86934444, 0.17419619],
       [0.8686147 , 0.17346544],
       [0.86900615, 0.17296181],
       [0.86810129, 0.17384088],
       [0.86819126, 0.17336125],
       [0.86948257, 0.17396413],
       [0.86961591, 0.17399845],
       [0.86897316, 0.17398366],
       [0.86938572, 0.17316687],
       [0.86906173, 0.17284797],
       [0.8691096 , 0.17420637],
       [0.86959023, 0.17403691],
       [0.86905049, 0.17284716],
       [0.8691788 , 0.17324714],
       [0.86911659, 0.17425868],
       [0.86813462, 0.17387791],
       [0.86851414, 0.17348041],
       [0.86785409, 0.17405381],
       [0.86903108, 0.17363745],
       [0.86961647, 0.17420163],
       [0.86911984, 0.17328696],
       [0.8684429 , 0.17361285],
       [0.86845334, 0.17332358],
       [0.86952999, 0.17383767],
       [0.8685355 , 0.1733606 ],
       [0.86892317, 0.17334928],
       [0.86925321, 0.17440156],
       [0.86901109, 0.17339757],
       [0.8682272 , 0.17381474],
       [0.86905614, 0.17364664],
       [0.86779446, 0.17399134],
       [0.86891708, 0.17296344],
       [0.86882035, 0.173203  ],
       [0.86825027, 0.17343679],
       [0.86920367, 0.17417066],
       [0.86955816, 0.1739604 ],
       [0.86930445, 0.1725178 ],
       [0.86849692, 0.1738836 ],
       [0.86801964, 0.17378781],
       [0.86893865, 0.17316923],
       [0.86928274, 0.17384211],
       [0.86897911, 0.1733487 ],
       [0.86867054, 0.17377444],
       [0.86881517, 0.17319682],
       [0.86935914, 0.17411766],
       [0.86895333, 0.17333866],
       [0.86927493, 0.17276833],
       [0.86922388, 0.17318921]])

In [28]:
dist_matrix = pd.DataFrame(dist.pairwise(DF[["lat", "lon"]].to_numpy())*6378100, columns=DF.PuP_ID.unique(), index=DF.PuP_ID.unique())
dist_matrix.round(1)

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
1,0.0,9277.1,1333.8,4497.3,4187.0,7407.3,7179.0,1432.3,2294.2,1875.8,...,7937.3,3642.3,266.5,2894.4,3807.1,4058.1,1094.7,3031.0,4652.3,2929.3
2,9277.1,0.0,9792.9,5685.1,8869.3,2063.7,3774.4,10666.4,11512.2,7416.8,...,1747.6,8078.5,9428.3,8008.6,5607.3,7330.5,9873.9,7871.5,10751.4,9701.9
3,1333.8,9792.9,0.0,5542.3,5520.8,8062.9,8119.3,1299.4,1913.2,2524.5,...,8615.5,4957.2,1509.6,4195.5,4635.7,5322.2,336.5,4322.8,5894.0,4215.7
4,4497.3,5685.1,5542.3,0.0,3245.9,3621.7,2734.7,5903.9,6752.3,3127.7,...,4021.1,2399.5,4534.4,2373.4,1321.8,1690.9,5455.0,2222.0,5096.3,4048.5
5,4187.0,8869.3,5520.8,3245.9,0.0,6813.5,5451.7,5124.2,5773.4,4212.9,...,7153.4,956.5,4030.7,1602.4,3972.7,1555.7,5264.1,1587.9,1890.3,1674.9
6,7407.3,2063.7,8062.9,3621.7,6813.5,0.0,2058.6,8824.6,9682.2,5591.9,...,564.8,6015.1,7535.4,5954.7,3641.1,5270.1,8103.3,5815.0,8692.1,7646.7
7,7179.0,3774.4,8119.3,2734.7,5451.7,2058.6,0.0,8602.2,9457.9,5607.6,...,2071.2,4832.1,7237.9,5025.3,3499.0,4036.6,8074.1,4861.5,7330.5,6624.2
8,1432.3,10666.4,1299.4,5903.9,5124.2,8824.6,8602.2,0.0,862.1,3250.1,...,9358.9,4769.0,1369.9,4090.1,5237.7,5300.8,1009.5,4245.4,5096.7,3591.0
9,2294.2,11512.2,1913.2,6752.3,5773.4,9682.2,9457.9,862.1,0.0,4100.0,...,10218.1,5505.5,2220.3,4863.1,6099.8,6080.6,1709.6,5023.4,5509.9,4164.6
10,1875.8,7416.8,2524.5,3127.7,4212.9,5591.9,5607.6,3250.1,4100.0,0.0,...,6134.9,3360.9,2058.8,2614.9,2113.7,3393.4,2522.9,2659.0,5361.0,3640.9
11,3112.4,10698.6,4244.7,5069.0,2564.0,8649.9,7660.4,3338.7,3723.7,4269.7,...,9080.7,2851.5,2855.8,2699.3,5202.5,3641.2,3917.0,2847.1,1786.2,1036.3
12,4509.1,9416.5,5835.7,3820.5,587.7,7366.0,5940.9,5321.0,5909.1,4710.2,...,7692.1,1538.2,4328.6,2128.0,4558.9,2130.0,5560.4,2135.5,1398.8,1744.5
13,1598.0,8300.7,1498.4,4390.2,5166.6,6605.0,6813.7,2579.4,3340.8,1264.2,...,7162.5,4407.4,1862.3,3628.1,3317.5,4561.6,1633.0,3709.2,6013.2,4250.4
14,2169.4,11345.8,1699.2,6652.0,5784.6,9530.9,9346.5,749.1,227.8,3941.8,...,10069.8,5479.8,2118.7,4818.5,5964.6,6033.0,1510.9,4976.2,5594.8,4199.0
15,4533.1,9357.7,5861.5,3769.5,550.3,7308.3,5875.2,5360.5,5954.9,4705.5,...,7632.0,1505.8,4355.7,2114.7,4522.9,2079.9,5588.4,2116.6,1467.8,1790.6
16,2732.9,9347.0,4047.0,3708.4,1610.2,7294.7,6316.1,3530.3,4163.5,3303.9,...,7721.4,1564.9,2537.4,1340.5,3901.8,2328.5,3763.5,1486.6,2064.2,373.6
17,1749.6,8363.2,1475.8,4573.7,5385.9,6700.5,6964.1,2630.3,3360.0,1455.8,...,7260.4,4627.2,2015.9,3848.0,3474.3,4776.5,1652.3,3928.6,6217.8,4455.6
18,7191.4,2198.4,7826.9,3502.1,6718.8,261.7,2160.0,8604.7,9460.9,5366.0,...,822.0,5901.1,7324.4,5810.8,3444.7,5168.8,7872.3,5674.8,8589.9,7504.3
19,5071.3,5085.3,6060.8,644.4,3796.1,3023.3,2117.1,6489.9,7343.8,3587.2,...,3398.9,2995.6,5123.5,3014.9,1569.2,2247.5,5994.4,2861.4,5669.6,4683.0
20,9003.0,274.8,9523.7,5423.6,8616.1,1804.6,3574.3,10393.2,11239.4,7143.4,...,1522.4,7819.0,9153.8,7741.4,5333.2,7074.4,9603.0,7605.2,10496.2,9434.9
21,1823.2,7974.5,3047.2,2748.5,2786.5,5989.2,5476.0,3178.1,4015.2,1472.6,...,6480.7,2016.1,1812.8,1234.3,2367.7,2277.9,2878.6,1326.5,3901.5,2217.6
22,2582.2,11526.7,1735.2,7071.8,6418.4,9777.5,9726.6,1297.9,836.0,4200.1,...,10326.3,6062.2,2592.3,5371.3,6284.3,6574.9,1677.3,5523.3,6288.1,4861.2
23,2675.4,8937.2,4007.6,3304.6,1522.5,6885.6,5930.5,3622.4,4311.2,3017.3,...,7314.3,1253.2,2510.5,932.9,3498.9,1978.4,3744.7,1083.1,2353.0,776.1
24,5355.3,4435.0,6231.7,1252.8,4482.9,2372.9,1910.8,6787.0,7648.2,3710.9,...,2794.3,3652.0,5439.1,3588.9,1597.2,2928.2,6202.6,3445.9,6344.9,5277.9
25,5675.3,5104.8,6724.3,1183.6,3827.8,3096.3,1678.7,7074.6,7918.6,4287.7,...,3363.3,3160.0,5704.8,3355.0,2317.2,2366.1,6638.6,3189.6,5717.4,4945.7
26,1727.0,11000.4,1891.5,6035.6,4915.4,9112.4,8761.1,601.9,859.1,3602.0,...,9635.3,4668.7,1577.0,4049.2,5487.8,5267.5,1585.9,4212.7,4692.1,3306.8
27,5136.0,5451.3,6201.6,664.6,3421.8,3404.0,2195.6,6531.7,7374.4,3791.8,...,3731.6,2689.4,5162.0,2829.8,1910.0,1907.1,6108.6,2666.5,5309.5,4446.9
28,3127.7,7677.0,4401.9,2024.7,1681.0,5619.7,4668.4,4374.5,5163.6,2631.7,...,6039.4,748.0,3062.2,356.8,2379.6,932.0,4211.8,197.3,3279.4,2028.1
29,2072.2,9300.7,1026.2,5607.6,6133.4,7701.5,8014.9,2319.8,2846.8,2480.1,...,8264.1,5456.0,2310.6,4674.0,4525.4,5693.2,1349.8,4775.8,6724.4,4994.1
30,2610.2,8128.4,3915.3,2543.6,1794.5,6083.4,5231.1,3805.5,4582.4,2425.4,...,6524.7,1047.6,2520.2,286.5,2669.6,1498.3,3703.5,441.1,3089.1,1605.6
31,6609.4,2842.9,7297.0,2860.1,6085.1,810.3,1883.1,8030.5,8889.6,4808.4,...,1328.5,5259.5,6733.3,5165.8,2832.5,4532.6,7326.6,5029.5,7951.8,6859.2
32,1672.9,8122.4,2915.3,2912.7,2837.8,6142.5,5640.2,3017.5,3852.8,1485.2,...,6636.4,2103.8,1654.2,1321.5,2515.1,2407.0,2737.6,1427.7,3875.8,2165.9
33,9368.3,316.0,9921.9,5662.8,8816.0,2052.9,3626.7,10767.5,11617.4,7517.9,...,1663.4,8045.7,9512.3,8006.4,5658.8,7287.2,9993.2,7865.5,10702.8,9697.5
34,4433.7,8382.8,5760.9,2827.5,568.1,6335.8,4910.9,5475.3,6165.9,4216.3,...,6655.9,858.5,4304.2,1635.0,3691.9,1160.3,5525.4,1562.3,2419.6,2166.4
35,4016.7,7347.0,5281.6,1699.7,1546.2,5286.0,4065.0,5259.1,6039.0,3359.4,...,5646.9,767.2,3952.5,1177.0,2540.3,41.7,5098.1,1015.6,3407.2,2574.4
36,6727.5,3808.6,7647.6,2327.4,5203.0,1917.5,488.4,8154.3,9012.1,5131.6,...,2063.3,4526.8,6793.6,4662.8,3020.1,3736.2,7608.2,4502.4,7091.6,6293.0
37,1181.2,8890.7,904.0,4748.2,5134.0,7161.1,7267.2,1971.6,2723.2,1659.6,...,7714.8,4456.2,1443.4,3674.8,3771.5,4713.7,1015.3,3779.4,5790.5,4042.3
38,1905.8,11148.8,1673.3,6353.2,5412.2,9305.1,9060.7,482.4,400.3,3732.4,...,9838.5,5120.5,1822.8,4469.9,5712.9,5686.7,1424.8,4629.4,5228.1,3823.6
39,5689.1,11455.2,6913.0,5880.5,2638.4,9412.2,7904.4,6060.1,6409.1,6394.1,...,9722.2,3554.7,5452.9,4000.9,6566.7,4189.8,6594.3,4054.1,1048.3,2811.1
40,4880.5,4434.4,5556.7,1879.4,4996.4,2529.5,2904.1,6295.3,7152.7,3065.3,...,3069.6,4073.8,5015.0,3783.2,1195.2,3481.9,5583.2,3675.9,6761.5,5447.6
41,7937.3,1747.6,8615.5,4021.1,7153.4,564.8,2071.2,9358.9,10218.1,6134.9,...,0.0,6391.6,8059.3,6381.4,4151.9,5628.0,8650.8,6236.1,9040.9,8066.9
42,3642.3,8078.5,4957.2,2399.5,956.5,6015.1,4832.1,4769.0,5505.5,3360.9,...,6391.6,0.0,3534.3,782.8,3022.8,795.7,4737.0,704.0,2706.4,1821.1
43,266.5,9428.3,1509.6,4534.4,4030.7,7535.4,7237.9,1369.9,2220.3,2058.8,...,8059.3,3534.3,0.0,2806.6,3914.6,3994.1,1234.4,2951.4,4420.3,2713.7
44,2894.4,8008.6,4195.5,2373.4,1602.4,5954.7,5025.3,4090.1,4863.1,2614.9,...,6381.4,782.8,2806.6,0.0,2635.9,1218.4,3987.1,169.5,3044.5,1693.6
45,3807.1,5607.3,4635.7,1321.8,3972.7,3641.1,3499.0,5237.7,6099.8,2113.7,...,4151.9,3022.8,3914.6,2635.9,0.0,2551.7,4613.7,2544.5,5658.9,4273.6
46,4058.1,7330.5,5322.2,1690.9,1555.7,5270.1,4036.6,5300.8,6080.6,3393.4,...,5628.0,795.7,3994.1,1218.4,2551.7,0.0,5139.2,1057.2,3422.2,2607.0
47,1094.7,9873.9,336.5,5455.0,5264.1,8103.3,8074.1,1009.5,1709.6,2522.9,...,8650.8,4737.0,1234.4,3987.1,4613.7,5139.2,0.0,4121.2,5579.9,3917.9
48,3031.0,7871.5,4322.8,2222.0,1587.9,5815.0,4861.5,4245.4,5023.4,2659.0,...,6236.1,704.0,2951.4,169.5,2544.5,1057.2,4121.2,0.0,3117.8,1832.0
49,4652.3,10751.4,5894.0,5096.3,1890.3,8692.1,7330.5,5096.7,5509.9,5361.0,...,9040.9,2706.4,4420.3,3044.5,5658.9,3422.2,5579.9,3117.8,0.0,1762.8
50,2929.3,9701.9,4215.7,4048.5,1674.9,7646.7,6624.2,3591.0,4164.6,3640.9,...,8066.9,1821.1,2713.7,1693.6,4273.6,2607.0,3917.9,1832.0,1762.8,0.0

In [29]:
objective_function = lpSum(dist_matrix.loc[i,j] * y[i][j] for i in I for j in J)

In [30]:
model += objective_function

In [ ]:
model

In [32]:
#Constraint 1
for j in J:
    model += lpSum(y[i][j] for i in I) == 1

In [33]:
P = 2

In [34]:
#Constraint 2
for j in J:
    model += lpSum(x[j] for i in I) == P

In [35]:
#Constraint 3 - takes forever to execute 10 min +
for j in J:
    model += lpSum(set_of_all_customers.loc[i].Demand_C * y[i][j] for i in I) <= set_of_all_pup.loc[j].Capacity_pup * x[j]

In [36]:
model.solve()
LpStatus[model.status]

'Infeasible'

In [ ]:
print("The following Pickup-Points are established:")
for j in J:
    if x[j].varValue >= 0.1:
        print("-{}".format(set_of_all_pup.loc[j].name))

![](https://i.imgur.com/Nd4031p.png)

Set of customers and PuP is identical

- Decision Variables:
    - yij = if customer i is assigned to PuP j 1;0
    - xj = if PuP j is opened or not 1;0
- Parameters:
    - P = Number of PuPs
    - cij = Shipment cost from PuP to Customer
    - di = Demand of customer i
    - qj = Capacity of PuP j